# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'Social Distance Alarm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social Distance Alarm
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

  target 'Social Distance AlarmTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'UNTIL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social Distance Alarm
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

end
